version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: bacuaban77/app:latest
    container_name: app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@${NEXT_PUBLIC_SERVER_IP}:5432/fullstack
      - NEXT_PUBLIC_SERVER_IP=${NEXT_PUBLIC_SERVER_IP}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '3000:3000'
  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_ADMIN_USER=${ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - '8443:8443'
      - '8080:8080'
      - '9990:9990'
    volumes:
      - /path/to/init-scripts:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
