version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - SUBDOMAINS=workload
      - TOKEN=$DUCKDNS_TOKEN
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  app:
    image: bacuaban77/app:latest
    container_name: app
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/fullstack?sslmode=disable"
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '9990:3000'
volumes:
  db:
    driver: local